//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satranc_v27.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egitimler()
        {
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int egitim_id { get; set; }
        public string egitim_adi { get; set; }
        public Nullable<System.DateTime> egitim_tarihi { get; set; }
        public Nullable<int> egitim_suresi { get; set; }
        public Nullable<decimal> egitim_fiyati { get; set; }
        public string egitim_gorsel_url { get; set; }
        public Nullable<bool> egitim_aktif { get; set; }
        public string egitim_aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}
