//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satranc_v27.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.SiparisDetaylari = new HashSet<SiparisDetaylari>();
        }
    
        public int siparis_id { get; set; }
        public Nullable<int> alici_id { get; set; }
        public Nullable<System.DateTime> siparis_tarihi { get; set; }
        public decimal toplam_tutar { get; set; }
        public string odeme_durumu { get; set; }
        public string kargo_durumu { get; set; }
        public string teslimat_adresi { get; set; }
    
        public virtual Alicilar Alicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetaylari> SiparisDetaylari { get; set; }
    }
}
