//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satranc_v27.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Sepet = new HashSet<Sepet>();
            this.SiparisDetaylari = new HashSet<SiparisDetaylari>();
            this.Yorumlar = new HashSet<Yorumlar>();
            this.Egitimler = new HashSet<Egitimler>();
        }
    
        public int urun_id { get; set; }
        public string urun_adi { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public decimal fiyat { get; set; }
        public int stok_miktari { get; set; }
        public string aciklama { get; set; }
        public string gorsel_url { get; set; }
        public Nullable<System.DateTime> eklenme_tarihi { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<int> satici_id { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetaylari> SiparisDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egitimler> Egitimler { get; set; }
        public virtual Saticilar Saticilar { get; set; }
    }
}
