//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satranc_v27.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int yorum_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<int> alici_id { get; set; }
        public string yorum_metni { get; set; }
        public Nullable<byte> puan { get; set; }
        public Nullable<System.DateTime> yorum_tarihi { get; set; }
    
        public virtual Alicilar Alicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
